import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useSelector } from 'react-redux'
import CountryCard from '../components/countryCard'
import { useEffect } from 'react'
import { useRouter } from 'next/router'

export default function Home () {
  useEffect(() => {
    if (user.user_n_email == null) {
      router.push('/auth/sign-in')
    }
  }, [])

  const stateSlots = useSelector(state => state.countries)
  const user = useSelector(state => state.user)
  const router = useRouter()

  let filterWithRegion
  if (stateSlots.activeRegion == null) {
    filterWithRegion = stateSlots.list
  } else {
    filterWithRegion = stateSlots.list.filter((item, i) => {
      return item.region == stateSlots.activeRegion
    })
  }

  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Countries with flag list</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
      </div>
      <section className='container countries'>
        <div className='row'>
          {filterWithRegion?.map((country, i) => (
            <CountryCard key={i} country={country} />
          ))}
        </div>
      </section>
    </>
  )
}
